#!/bin/bash

INSTALL=

if [ $UID != 0 ];
then
	echo "Must be root! (try 'sudo max-chgname')"
	exit 0
fi

if [ ! $1 ];
then
	echo "Usage: max-chgname [new name]"
	echo "* Changes the name of the robot"
	exit 0
fi

. $INSTALL/config
OLD=`cat /etc/hostname`
NEW=$MODEL-$1

echo -n "Changing name from '$OLD' to '$NEW'...  "

cp -f /etc/hosts /etc/hosts~
echo $NEW > /etc/hostname
sed 's|'"$OLD"'|'"$NEW"'|g' /etc/hosts >/etc/hosts.new && mv -f /etc/hosts.new /etc/hosts
hostname -F /etc/hostname

echo "Done."

