OBJECTS		= syscall.o
PACKAGES	= glib-2.0

TARGET		= max-syscall
LIBS		= $(shell pkg-config --libs $(PACKAGES)) -L../libmax -lmax
CFLAGS		= -pipe -ggdb3 -Wall -I. -I.. -I../libmax $(shell pkg-config --cflags $(PACKAGES))

all: $(OBJECTS)
	$(CC) -o $(TARGET) $(OBJECTS) $(LIBS)
	rm -f $(OBJECTS)

clean:
	rm -f $(TARGET)

%.o: %.c
	$(CC) -c $(CFLAGS) $*.c -o $*.o

