
all:
	$(MAKE) -f Makefile.modinfo all
	$(MAKE) -f Makefile.syscall all
	$(MAKE) -f Makefile.log all
	$(MAKE) -f Makefile.autostart all
	$(MAKE) -f Makefile.client all

clean:
	$(MAKE) -f Makefile.modinfo clean
	$(MAKE) -f Makefile.syscall clean
	$(MAKE) -f Makefile.log clean
	$(MAKE) -f Makefile.autostart clean
	$(MAKE) -f Makefile.client clean

