OBJECTS		= modinfo.o meta.o math.o
PACKAGES	= glib-2.0 gmodule-2.0 libmatheval

TARGET		= max-modinfo
LIBS		= $(shell pkg-config --libs $(PACKAGES)) -lbfd -laul -L../aul
CFLAGS		= -pipe -ggdb3 -Wall -I. -I.. -I../aul/include $(shell pkg-config --cflags $(PACKAGES))

all: $(OBJECTS)
	$(CC) -o $(TARGET) $(OBJECTS) $(LIBS)
	rm -f $(OBJECTS)

clean:
	rm -f $(TARGET)

%.o: %.c
	$(CC) -c $(CFLAGS) $*.c -o $*.o

%.o: ../%.c
	$(CC) -c $(CFLAGS) ../$*.c -o $*.o

