/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_senseta_MaxRobot */

#ifndef _Included_org_senseta_MaxRobot
#define _Included_org_senseta_MaxRobot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_senseta_MaxRobot
 * Method:    connect_local
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_senseta_MaxRobot_connect_1local
  (JNIEnv *, jclass);

/*
 * Class:     org_senseta_MaxRobot
 * Method:    syscall
 * Signature: (ILjava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_senseta_MaxRobot_syscall
  (JNIEnv *, jclass, jint, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
